name: Update Article List

on:
  push:
    paths:
      - 'ex_art/**'  # Trigger przy zmianie w folderze ex_art

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate article list
        run: |
          # Lista plików w ex_art/ (tylko dd.mm.yyyy.html)
          LIST=$(ls ex_art | grep -E '^[0-9]{2}\.[0-9]{2}\.[0-9]{4}\.html$')

          # Sortowanie od najnowszego
          SORTED_LIST=$(echo "$LIST" | awk -F. '{print $3"-"$2"-"$1 " " $0}' | sort -r | cut -d' ' -f2)

          # Zapisz do pliku JS
          echo "const articles = [" > js/articles.js
          for file in $SORTED_LIST; do
            echo "  \"$file\"," >> js/articles.js
          done
          echo "];" >> js/articles.js

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add js/articles.js
          git commit -m "Automatyczna aktualizacja listy artykułów"
          git push
